language: java
script: "mvn cobertura:cobertura"
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn -DskipTests=true clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)


branches:
  only:
    - master